/* Public booking + staff list. Empty URLs stay off until a real calendar link is added.
   Add or remove people here — shareable pages (profile.html?who=<slug>) and ratings follow the slug.
   Ratings are stored in the client-portal database, keyed by this slug, not by a portal login. */
window.SH_BOOKINGS = {
  pageUrl: "",
  maxOpensPerHour: 6,
  ratingsApi: "https://victorious-sky-0924e120f.7.azurestaticapps.net/api/public/staff",
  staff: [
    {
      published: true,
      slug: "hanna-joice",
      name: "Hanna Joice",
      title: "Co-Founder & Chief Executive Officer",
      specializations: ["Personal Tax Services", "Corporate Tax Services", "Tax Planning"],
      photo: "images/team/hanna-joice.jpg",
      bio: "Hanna Joice is the Co-Founder and Chief Executive Officer of SH Elevate Financial Group, where she leads the firm's vision, growth strategy, and commitment to delivering exceptional financial solutions. With expertise in taxation, financial planning, and business advisory, she combines strategic insight with a client-centered approach. Under her leadership, the firm continues to grow as a trusted partner for individuals, families, and business owners seeking clarity and sustainable financial growth.",
      email: "info@shelevate.ca",
      phone: "+1 (437) 925-6546",
      experience: "",
      location: "Scarborough, ON",
      languages: ["English"],
      bookingsUrl: "",
    },
    {
      published: true,
      slug: "stevens-sabu",
      name: "Stevens Sabu",
      title: "Co-Founder and Director",
      specializations: ["Corporate Tax Services", "Tax Planning"],
      photo: "images/team/stevens-sabu.jpg",
      bio: "Stevens Sabu serves as Co-Founder and Director at SH Elevate Financial Group, where he is dedicated to shaping the firm's vision, driving growth, and delivering trusted financial guidance. He works with individuals, families, and business owners on financial planning, taxation, and long-term wealth strategies. Known for his professional approach and attention to detail, Stevens focuses on clear guidance and strategies aligned with each client's goals.",
      email: "info@shelevate.ca",
      phone: "+1 (437) 925-6546",
      experience: "",
      location: "Scarborough, ON",
      languages: ["English"],
      bookingsUrl: "",
    },
    {
      published: true,
      slug: "mehakdeep-kaur",
      name: "Mehakdeep Kaur",
      title: "Senior Client Manager",
      specializations: ["Personal Tax Services", "Tax Planning"],
      photo: "images/team/mehakdeep-kaur.jpg",
      bio: "Mehakdeep Kaur is a Senior Client Manager at SH Elevate Financial Group, passionate about helping individuals, families, and business owners feel confident and supported with their taxes and financial matters. She takes the time to understand each client's situation and works to make the tax process simple and stress-free. Whether assisting with tax planning, compliance, or financial guidance, she is committed to delivering solutions that make a difference.",
      email: "info@shelevate.ca",
      phone: "+1 (437) 925-6546",
      experience: "",
      location: "Scarborough, ON",
      languages: ["English"],
      bookingsUrl: "",
    },
    {
      published: true,
      slug: "ginil-jose",
      name: "Ginil Jose",
      title: "Client Manager",
      specializations: ["Personal Tax Services", "Tax Planning"],
      photo: "images/team/ginil-jose.jpg",
      bio: "Ginil Jose serves as Client Manager at SH Elevate Financial Group, where he is dedicated to building strong client relationships and ensuring every individual receives personalized financial guidance. He works closely with individuals, families, and business owners to navigate tax and financial matters with confidence. Known for his approachable nature and attention to detail, Ginil helps clients understand tax strategies, government benefits, and financial opportunities.",
      email: "info@shelevate.ca",
      phone: "+1 (437) 925-6546",
      experience: "",
      location: "Scarborough, ON",
      languages: ["English"],
      bookingsUrl: "",
    },
  ],
};
